#!/usr/bin/env ruby
lib = File.expand_path("lib", __dir__)
$LOAD_PATH.unshift(lib)

require "fin_snap"

config_filename = ARGV.empty? ? "institutions.yml" : ARGV.shift
credentials_filename = ARGV.empty? ? "credentials.yml" : ARGV.shift

finsnap = FinSnap.new(config_filename, credentials_filename)
output = finsnap.run!
puts output
