#!/usr/bin/env ruby
lib = File.expand_path("lib", __dir__)
$LOAD_PATH.unshift(lib)

require "fin_snap"

config_filename = ARGV.empty? ? "sources.yml" : ARGV.shift
output = FinSnap.new(config_filename).run!
puts output
